// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Zapharaos/go-spit (interfaces: Spreadsheet)
//
// Generated by this command:
//
//	mockgen -destination=spreadsheet_mock.go -package=spit . Spreadsheet
//

// Package spit is a generated GoMock package.
package spit

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSpreadsheet is a mock of Spreadsheet interface.
type MockSpreadsheet struct {
	ctrl     *gomock.Controller
	recorder *MockSpreadsheetMockRecorder
	isgomock struct{}
}

// MockSpreadsheetMockRecorder is the mock recorder for MockSpreadsheet.
type MockSpreadsheetMockRecorder struct {
	mock *MockSpreadsheet
}

// NewMockSpreadsheet creates a new mock instance.
func NewMockSpreadsheet(ctrl *gomock.Controller) *MockSpreadsheet {
	mock := &MockSpreadsheet{ctrl: ctrl}
	mock.recorder = &MockSpreadsheetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpreadsheet) EXPECT() *MockSpreadsheetMockRecorder {
	return m.recorder
}

// applyBorderToCell mocks base method.
func (m *MockSpreadsheet) ApplyBorderToCell(col, row int, side string, border *Border) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyBorderToCell", col, row, side, border)
	ret0, _ := ret[0].(error)
	return ret0
}

// applyBorderToCell indicates an expected call of applyBorderToCell.
func (mr *MockSpreadsheetMockRecorder) applyBorderToCell(col, row, side, border any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyBorderToCell", reflect.TypeOf((*MockSpreadsheet)(nil).ApplyBorderToCell), col, row, side, border)
}

// applyBordersToRange mocks base method.
func (m *MockSpreadsheet) ApplyBordersToRange(startCol, startRow, endCol, endRow int, borders Borders) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyBordersToRange", startCol, startRow, endCol, endRow, borders)
	ret0, _ := ret[0].(error)
	return ret0
}

// applyBordersToRange indicates an expected call of applyBordersToRange.
func (mr *MockSpreadsheetMockRecorder) applyBordersToRange(startCol, startRow, endCol, endRow, borders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyBordersToRange", reflect.TypeOf((*MockSpreadsheet)(nil).ApplyBordersToRange), startCol, startRow, endCol, endRow, borders)
}

// applyStyleToCell mocks base method.
func (m *MockSpreadsheet) ApplyStyleToCell(col, row int, style Style) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyStyleToCell", col, row, style)
	ret0, _ := ret[0].(error)
	return ret0
}

// applyStyleToCell indicates an expected call of applyStyleToCell.
func (mr *MockSpreadsheetMockRecorder) applyStyleToCell(col, row, style any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyStyleToCell", reflect.TypeOf((*MockSpreadsheet)(nil).ApplyStyleToCell), col, row, style)
}

// applyStyleToRange mocks base method.
func (m *MockSpreadsheet) ApplyStyleToRange(startCol, startRow, endCol, endRow int, style Style) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyStyleToRange", startCol, startRow, endCol, endRow, style)
	ret0, _ := ret[0].(error)
	return ret0
}

// applyStyleToRange indicates an expected call of applyStyleToRange.
func (mr *MockSpreadsheetMockRecorder) applyStyleToRange(startCol, startRow, endCol, endRow, style any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyStyleToRange", reflect.TypeOf((*MockSpreadsheet)(nil).ApplyStyleToRange), startCol, startRow, endCol, endRow, style)
}

// close mocks base method.
func (m *MockSpreadsheet) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// close indicates an expected call of close.
func (mr *MockSpreadsheetMockRecorder) close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSpreadsheet)(nil).Close))
}

// createNewFile mocks base method.
func (m *MockSpreadsheet) CreateNewFile() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewFile")
	ret0, _ := ret[0].(error)
	return ret0
}

// createNewFile indicates an expected call of createNewFile.
func (mr *MockSpreadsheetMockRecorder) createNewFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewFile", reflect.TypeOf((*MockSpreadsheet)(nil).CreateNewFile))
}

// createSheet mocks base method.
func (m *MockSpreadsheet) CreateSheet() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSheet")
	ret0, _ := ret[0].(error)
	return ret0
}

// createSheet indicates an expected call of createSheet.
func (mr *MockSpreadsheetMockRecorder) createSheet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSheet", reflect.TypeOf((*MockSpreadsheet)(nil).CreateSheet))
}

// getCellValue mocks base method.
func (m *MockSpreadsheet) GetCellValue(col, row int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCellValue", col, row)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getCellValue indicates an expected call of getCellValue.
func (mr *MockSpreadsheetMockRecorder) getCellValue(col, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCellValue", reflect.TypeOf((*MockSpreadsheet)(nil).GetCellValue), col, row)
}

// getColumnLetter mocks base method.
func (m *MockSpreadsheet) GetColumnLetter(col int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetColumnLetter", col)
	ret0, _ := ret[0].(string)
	return ret0
}

// getColumnLetter indicates an expected call of getColumnLetter.
func (mr *MockSpreadsheetMockRecorder) getColumnLetter(col any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetColumnLetter", reflect.TypeOf((*MockSpreadsheet)(nil).GetColumnLetter), col)
}

// getFile mocks base method.
func (m *MockSpreadsheet) GetFile() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile")
	ret0, _ := ret[0].(any)
	return ret0
}

// getFile indicates an expected call of getFile.
func (mr *MockSpreadsheetMockRecorder) getFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockSpreadsheet)(nil).GetFile))
}

// getSheetName mocks base method.
func (m *MockSpreadsheet) GetSheetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSheetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// getSheetName indicates an expected call of getSheetName.
func (mr *MockSpreadsheetMockRecorder) getSheetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSheetName", reflect.TypeOf((*MockSpreadsheet)(nil).GetSheetName))
}

// getTable mocks base method.
func (m *MockSpreadsheet) GetTable() *Table {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTable")
	ret0, _ := ret[0].(*Table)
	return ret0
}

// getTable indicates an expected call of getTable.
func (mr *MockSpreadsheetMockRecorder) getTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTable", reflect.TypeOf((*MockSpreadsheet)(nil).GetTable))
}

// hasExistingBorder mocks base method.
func (m *MockSpreadsheet) HasExistingBorder(col, row int, side string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasExistingBorder", col, row, side)
	ret0, _ := ret[0].(bool)
	return ret0
}

// hasExistingBorder indicates an expected call of hasExistingBorder.
func (mr *MockSpreadsheetMockRecorder) hasExistingBorder(col, row, side any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasExistingBorder", reflect.TypeOf((*MockSpreadsheet)(nil).HasExistingBorder), col, row, side)
}

// isCellMerged mocks base method.
func (m *MockSpreadsheet) IsCellMerged(col, row int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCellMerged", col, row)
	ret0, _ := ret[0].(bool)
	return ret0
}

// isCellMerged indicates an expected call of isCellMerged.
func (mr *MockSpreadsheetMockRecorder) isCellMerged(col, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCellMerged", reflect.TypeOf((*MockSpreadsheet)(nil).IsCellMerged), col, row)
}

// isCellMergedHorizontally mocks base method.
func (m *MockSpreadsheet) IsCellMergedHorizontally(col, row int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCellMergedHorizontally", col, row)
	ret0, _ := ret[0].(bool)
	return ret0
}

// isCellMergedHorizontally indicates an expected call of isCellMergedHorizontally.
func (mr *MockSpreadsheetMockRecorder) isCellMergedHorizontally(col, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCellMergedHorizontally", reflect.TypeOf((*MockSpreadsheet)(nil).IsCellMergedHorizontally), col, row)
}

// mergeCells mocks base method.
func (m *MockSpreadsheet) MergeCells(startCol, startRow, endCol, endRow int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeCells", startCol, startRow, endCol, endRow)
	ret0, _ := ret[0].(error)
	return ret0
}

// mergeCells indicates an expected call of mergeCells.
func (mr *MockSpreadsheetMockRecorder) mergeCells(startCol, startRow, endCol, endRow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeCells", reflect.TypeOf((*MockSpreadsheet)(nil).MergeCells), startCol, startRow, endCol, endRow)
}

// processValue mocks base method.
func (m *MockSpreadsheet) ProcessValue(value any, format string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessValue", value, format)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// processValue indicates an expected call of processValue.
func (mr *MockSpreadsheetMockRecorder) processValue(value, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessValue", reflect.TypeOf((*MockSpreadsheet)(nil).ProcessValue), value, format)
}

// saveToWriter mocks base method.
func (m *MockSpreadsheet) SaveToWriter(writer io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToWriter", writer)
	ret0, _ := ret[0].(error)
	return ret0
}

// saveToWriter indicates an expected call of saveToWriter.
func (mr *MockSpreadsheetMockRecorder) saveToWriter(writer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToWriter", reflect.TypeOf((*MockSpreadsheet)(nil).SaveToWriter), writer)
}

// setActiveSheet mocks base method.
func (m *MockSpreadsheet) SetActiveSheet() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActiveSheet")
	ret0, _ := ret[0].(error)
	return ret0
}

// setActiveSheet indicates an expected call of setActiveSheet.
func (mr *MockSpreadsheetMockRecorder) setActiveSheet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActiveSheet", reflect.TypeOf((*MockSpreadsheet)(nil).SetActiveSheet))
}

// setCellValue mocks base method.
func (m *MockSpreadsheet) SetCellValue(col, row int, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCellValue", col, row, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// setCellValue indicates an expected call of setCellValue.
func (mr *MockSpreadsheetMockRecorder) setCellValue(col, row, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCellValue", reflect.TypeOf((*MockSpreadsheet)(nil).SetCellValue), col, row, value)
}

// setColumnWidth mocks base method.
func (m *MockSpreadsheet) SetColumnWidth(colLetter string, width float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetColumnWidth", colLetter, width)
	ret0, _ := ret[0].(error)
	return ret0
}

// setColumnWidth indicates an expected call of setColumnWidth.
func (mr *MockSpreadsheetMockRecorder) setColumnWidth(colLetter, width any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetColumnWidth", reflect.TypeOf((*MockSpreadsheet)(nil).SetColumnWidth), colLetter, width)
}

// setSheetName mocks base method.
func (m *MockSpreadsheet) SetSheetName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSheetName", name)
}

// setSheetName indicates an expected call of setSheetName.
func (mr *MockSpreadsheetMockRecorder) setSheetName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSheetName", reflect.TypeOf((*MockSpreadsheet)(nil).SetSheetName), name)
}
