// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Zapharaos/go-spit (interfaces: TableOperations)
//
// Generated by this command:
//
//	mockgen -destination=table_mock.go -package=spit . TableOperations
//

// Package spit is a generated GoMock package.
package spit

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTableOperations is a mock of TableOperations interface.
type MockTableOperations struct {
	ctrl     *gomock.Controller
	recorder *MockTableOperationsMockRecorder
	isgomock struct{}
}

// MockTableOperationsMockRecorder is the mock recorder for MockTableOperations.
type MockTableOperationsMockRecorder struct {
	mock *MockTableOperations
}

// NewMockTableOperations creates a new mock instance.
func NewMockTableOperations(ctrl *gomock.Controller) *MockTableOperations {
	mock := &MockTableOperations{ctrl: ctrl}
	mock.recorder = &MockTableOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableOperations) EXPECT() *MockTableOperationsMockRecorder {
	return m.recorder
}

// applyBorderToCell mocks base method.
func (m *MockTableOperations) ApplyBorderToCell(col, row int, side string, border *Border) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyBorderToCell", col, row, side, border)
	ret0, _ := ret[0].(error)
	return ret0
}

// applyBorderToCell indicates an expected call of applyBorderToCell.
func (mr *MockTableOperationsMockRecorder) applyBorderToCell(col, row, side, border any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyBorderToCell", reflect.TypeOf((*MockTableOperations)(nil).ApplyBorderToCell), col, row, side, border)
}

// applyBordersToRange mocks base method.
func (m *MockTableOperations) ApplyBordersToRange(startCol, startRow, endCol, endRow int, borders Borders) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyBordersToRange", startCol, startRow, endCol, endRow, borders)
	ret0, _ := ret[0].(error)
	return ret0
}

// applyBordersToRange indicates an expected call of applyBordersToRange.
func (mr *MockTableOperationsMockRecorder) applyBordersToRange(startCol, startRow, endCol, endRow, borders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyBordersToRange", reflect.TypeOf((*MockTableOperations)(nil).ApplyBordersToRange), startCol, startRow, endCol, endRow, borders)
}

// applyStyleToCell mocks base method.
func (m *MockTableOperations) ApplyStyleToCell(col, row int, style Style) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyStyleToCell", col, row, style)
	ret0, _ := ret[0].(error)
	return ret0
}

// applyStyleToCell indicates an expected call of applyStyleToCell.
func (mr *MockTableOperationsMockRecorder) applyStyleToCell(col, row, style any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyStyleToCell", reflect.TypeOf((*MockTableOperations)(nil).ApplyStyleToCell), col, row, style)
}

// applyStyleToRange mocks base method.
func (m *MockTableOperations) ApplyStyleToRange(startCol, startRow, endCol, endRow int, style Style) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyStyleToRange", startCol, startRow, endCol, endRow, style)
	ret0, _ := ret[0].(error)
	return ret0
}

// applyStyleToRange indicates an expected call of applyStyleToRange.
func (mr *MockTableOperationsMockRecorder) applyStyleToRange(startCol, startRow, endCol, endRow, style any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyStyleToRange", reflect.TypeOf((*MockTableOperations)(nil).ApplyStyleToRange), startCol, startRow, endCol, endRow, style)
}

// getCellValue mocks base method.
func (m *MockTableOperations) GetCellValue(col, row int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCellValue", col, row)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getCellValue indicates an expected call of getCellValue.
func (mr *MockTableOperationsMockRecorder) getCellValue(col, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCellValue", reflect.TypeOf((*MockTableOperations)(nil).GetCellValue), col, row)
}

// getColumnLetter mocks base method.
func (m *MockTableOperations) GetColumnLetter(col int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetColumnLetter", col)
	ret0, _ := ret[0].(string)
	return ret0
}

// getColumnLetter indicates an expected call of getColumnLetter.
func (mr *MockTableOperationsMockRecorder) getColumnLetter(col any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetColumnLetter", reflect.TypeOf((*MockTableOperations)(nil).GetColumnLetter), col)
}

// getTable mocks base method.
func (m *MockTableOperations) GetTable() *Table {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTable")
	ret0, _ := ret[0].(*Table)
	return ret0
}

// getTable indicates an expected call of getTable.
func (mr *MockTableOperationsMockRecorder) getTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTable", reflect.TypeOf((*MockTableOperations)(nil).GetTable))
}

// hasExistingBorder mocks base method.
func (m *MockTableOperations) HasExistingBorder(col, row int, side string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasExistingBorder", col, row, side)
	ret0, _ := ret[0].(bool)
	return ret0
}

// hasExistingBorder indicates an expected call of hasExistingBorder.
func (mr *MockTableOperationsMockRecorder) hasExistingBorder(col, row, side any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasExistingBorder", reflect.TypeOf((*MockTableOperations)(nil).HasExistingBorder), col, row, side)
}

// isCellMerged mocks base method.
func (m *MockTableOperations) IsCellMerged(col, row int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCellMerged", col, row)
	ret0, _ := ret[0].(bool)
	return ret0
}

// isCellMerged indicates an expected call of isCellMerged.
func (mr *MockTableOperationsMockRecorder) isCellMerged(col, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCellMerged", reflect.TypeOf((*MockTableOperations)(nil).IsCellMerged), col, row)
}

// isCellMergedHorizontally mocks base method.
func (m *MockTableOperations) IsCellMergedHorizontally(col, row int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCellMergedHorizontally", col, row)
	ret0, _ := ret[0].(bool)
	return ret0
}

// isCellMergedHorizontally indicates an expected call of isCellMergedHorizontally.
func (mr *MockTableOperationsMockRecorder) isCellMergedHorizontally(col, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCellMergedHorizontally", reflect.TypeOf((*MockTableOperations)(nil).IsCellMergedHorizontally), col, row)
}

// mergeCells mocks base method.
func (m *MockTableOperations) MergeCells(startCol, startRow, endCol, endRow int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeCells", startCol, startRow, endCol, endRow)
	ret0, _ := ret[0].(error)
	return ret0
}

// mergeCells indicates an expected call of mergeCells.
func (mr *MockTableOperationsMockRecorder) mergeCells(startCol, startRow, endCol, endRow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeCells", reflect.TypeOf((*MockTableOperations)(nil).MergeCells), startCol, startRow, endCol, endRow)
}

// processValue mocks base method.
func (m *MockTableOperations) ProcessValue(value any, format string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessValue", value, format)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// processValue indicates an expected call of processValue.
func (mr *MockTableOperationsMockRecorder) processValue(value, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessValue", reflect.TypeOf((*MockTableOperations)(nil).ProcessValue), value, format)
}

// setCellValue mocks base method.
func (m *MockTableOperations) SetCellValue(col, row int, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCellValue", col, row, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// setCellValue indicates an expected call of setCellValue.
func (mr *MockTableOperationsMockRecorder) setCellValue(col, row, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCellValue", reflect.TypeOf((*MockTableOperations)(nil).SetCellValue), col, row, value)
}
