// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Zapharaos/go-spit (interfaces: TableOperations)
//
// Generated by this command:
//
//	mockgen -destination=mocks/table_mock.go -package=mocks . TableOperations
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	spit "github.com/Zapharaos/go-spit"
	gomock "go.uber.org/mock/gomock"
)

// MockTableOperations is a mock of TableOperations interface.
type MockTableOperations struct {
	ctrl     *gomock.Controller
	recorder *MockTableOperationsMockRecorder
	isgomock struct{}
}

// MockTableOperationsMockRecorder is the mock recorder for MockTableOperations.
type MockTableOperationsMockRecorder struct {
	mock *MockTableOperations
}

// NewMockTableOperations creates a new mock instance.
func NewMockTableOperations(ctrl *gomock.Controller) *MockTableOperations {
	mock := &MockTableOperations{ctrl: ctrl}
	mock.recorder = &MockTableOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableOperations) EXPECT() *MockTableOperationsMockRecorder {
	return m.recorder
}

// ApplyBorderToCell mocks base method.
func (m *MockTableOperations) ApplyBorderToCell(col, row int, side string, border *spit.Border) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyBorderToCell", col, row, side, border)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyBorderToCell indicates an expected call of ApplyBorderToCell.
func (mr *MockTableOperationsMockRecorder) ApplyBorderToCell(col, row, side, border any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyBorderToCell", reflect.TypeOf((*MockTableOperations)(nil).ApplyBorderToCell), col, row, side, border)
}

// ApplyBordersToRange mocks base method.
func (m *MockTableOperations) ApplyBordersToRange(startCol, startRow, endCol, endRow int, borders spit.Borders) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyBordersToRange", startCol, startRow, endCol, endRow, borders)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyBordersToRange indicates an expected call of ApplyBordersToRange.
func (mr *MockTableOperationsMockRecorder) ApplyBordersToRange(startCol, startRow, endCol, endRow, borders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyBordersToRange", reflect.TypeOf((*MockTableOperations)(nil).ApplyBordersToRange), startCol, startRow, endCol, endRow, borders)
}

// ApplyStyleToCell mocks base method.
func (m *MockTableOperations) ApplyStyleToCell(col, row int, style spit.Style) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyStyleToCell", col, row, style)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyStyleToCell indicates an expected call of ApplyStyleToCell.
func (mr *MockTableOperationsMockRecorder) ApplyStyleToCell(col, row, style any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyStyleToCell", reflect.TypeOf((*MockTableOperations)(nil).ApplyStyleToCell), col, row, style)
}

// ApplyStyleToRange mocks base method.
func (m *MockTableOperations) ApplyStyleToRange(startCol, startRow, endCol, endRow int, style spit.Style) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyStyleToRange", startCol, startRow, endCol, endRow, style)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyStyleToRange indicates an expected call of ApplyStyleToRange.
func (mr *MockTableOperationsMockRecorder) ApplyStyleToRange(startCol, startRow, endCol, endRow, style any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyStyleToRange", reflect.TypeOf((*MockTableOperations)(nil).ApplyStyleToRange), startCol, startRow, endCol, endRow, style)
}

// GetCellValue mocks base method.
func (m *MockTableOperations) GetCellValue(col, row int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCellValue", col, row)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCellValue indicates an expected call of GetCellValue.
func (mr *MockTableOperationsMockRecorder) GetCellValue(col, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCellValue", reflect.TypeOf((*MockTableOperations)(nil).GetCellValue), col, row)
}

// GetColumnLetter mocks base method.
func (m *MockTableOperations) GetColumnLetter(col int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetColumnLetter", col)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetColumnLetter indicates an expected call of GetColumnLetter.
func (mr *MockTableOperationsMockRecorder) GetColumnLetter(col any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetColumnLetter", reflect.TypeOf((*MockTableOperations)(nil).GetColumnLetter), col)
}

// GetTable mocks base method.
func (m *MockTableOperations) GetTable() *spit.Table {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTable")
	ret0, _ := ret[0].(*spit.Table)
	return ret0
}

// GetTable indicates an expected call of GetTable.
func (mr *MockTableOperationsMockRecorder) GetTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTable", reflect.TypeOf((*MockTableOperations)(nil).GetTable))
}

// HasExistingBorder mocks base method.
func (m *MockTableOperations) HasExistingBorder(col, row int, side string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasExistingBorder", col, row, side)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasExistingBorder indicates an expected call of HasExistingBorder.
func (mr *MockTableOperationsMockRecorder) HasExistingBorder(col, row, side any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasExistingBorder", reflect.TypeOf((*MockTableOperations)(nil).HasExistingBorder), col, row, side)
}

// IsCellMerged mocks base method.
func (m *MockTableOperations) IsCellMerged(col, row int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCellMerged", col, row)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCellMerged indicates an expected call of IsCellMerged.
func (mr *MockTableOperationsMockRecorder) IsCellMerged(col, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCellMerged", reflect.TypeOf((*MockTableOperations)(nil).IsCellMerged), col, row)
}

// IsCellMergedHorizontally mocks base method.
func (m *MockTableOperations) IsCellMergedHorizontally(col, row int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCellMergedHorizontally", col, row)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCellMergedHorizontally indicates an expected call of IsCellMergedHorizontally.
func (mr *MockTableOperationsMockRecorder) IsCellMergedHorizontally(col, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCellMergedHorizontally", reflect.TypeOf((*MockTableOperations)(nil).IsCellMergedHorizontally), col, row)
}

// MergeCells mocks base method.
func (m *MockTableOperations) MergeCells(startCol, startRow, endCol, endRow int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeCells", startCol, startRow, endCol, endRow)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeCells indicates an expected call of MergeCells.
func (mr *MockTableOperationsMockRecorder) MergeCells(startCol, startRow, endCol, endRow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeCells", reflect.TypeOf((*MockTableOperations)(nil).MergeCells), startCol, startRow, endCol, endRow)
}

// ProcessValue mocks base method.
func (m *MockTableOperations) ProcessValue(value any, format string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessValue", value, format)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessValue indicates an expected call of ProcessValue.
func (mr *MockTableOperationsMockRecorder) ProcessValue(value, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessValue", reflect.TypeOf((*MockTableOperations)(nil).ProcessValue), value, format)
}

// SetCellValue mocks base method.
func (m *MockTableOperations) SetCellValue(col, row int, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCellValue", col, row, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCellValue indicates an expected call of SetCellValue.
func (mr *MockTableOperationsMockRecorder) SetCellValue(col, row, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCellValue", reflect.TypeOf((*MockTableOperations)(nil).SetCellValue), col, row, value)
}
