// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Zapharaos/go-spit (interfaces: tableOperations)
//
// Generated by this command:
//
//	mockgen -destination=mocks/table_mock.go -package=mocks . tableOperations
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	go_spit "github.com/Zapharaos/go-spit"
	gomock "go.uber.org/mock/gomock"
)

// MocktableOperations is a mock of tableOperations interface.
type MocktableOperations struct {
	ctrl     *gomock.Controller
	recorder *MocktableOperationsMockRecorder
	isgomock struct{}
}

// MocktableOperationsMockRecorder is the mock recorder for MocktableOperations.
type MocktableOperationsMockRecorder struct {
	mock *MocktableOperations
}

// NewMocktableOperations creates a new mock instance.
func NewMocktableOperations(ctrl *gomock.Controller) *MocktableOperations {
	mock := &MocktableOperations{ctrl: ctrl}
	mock.recorder = &MocktableOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktableOperations) EXPECT() *MocktableOperationsMockRecorder {
	return m.recorder
}

// applyBorderToCell mocks base method.
func (m *MocktableOperations) applyBorderToCell(col, row int, side string, border *go_spit.Border) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "applyBorderToCell", col, row, side, border)
	ret0, _ := ret[0].(error)
	return ret0
}

// applyBorderToCell indicates an expected call of applyBorderToCell.
func (mr *MocktableOperationsMockRecorder) applyBorderToCell(col, row, side, border any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "applyBorderToCell", reflect.TypeOf((*MocktableOperations)(nil).applyBorderToCell), col, row, side, border)
}

// applyBordersToRange mocks base method.
func (m *MocktableOperations) applyBordersToRange(startCol, startRow, endCol, endRow int, borders go_spit.Borders) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "applyBordersToRange", startCol, startRow, endCol, endRow, borders)
	ret0, _ := ret[0].(error)
	return ret0
}

// applyBordersToRange indicates an expected call of applyBordersToRange.
func (mr *MocktableOperationsMockRecorder) applyBordersToRange(startCol, startRow, endCol, endRow, borders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "applyBordersToRange", reflect.TypeOf((*MocktableOperations)(nil).applyBordersToRange), startCol, startRow, endCol, endRow, borders)
}

// applyStyleToCell mocks base method.
func (m *MocktableOperations) applyStyleToCell(col, row int, style go_spit.Style) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "applyStyleToCell", col, row, style)
	ret0, _ := ret[0].(error)
	return ret0
}

// applyStyleToCell indicates an expected call of applyStyleToCell.
func (mr *MocktableOperationsMockRecorder) applyStyleToCell(col, row, style any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "applyStyleToCell", reflect.TypeOf((*MocktableOperations)(nil).applyStyleToCell), col, row, style)
}

// applyStyleToRange mocks base method.
func (m *MocktableOperations) applyStyleToRange(startCol, startRow, endCol, endRow int, style go_spit.Style) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "applyStyleToRange", startCol, startRow, endCol, endRow, style)
	ret0, _ := ret[0].(error)
	return ret0
}

// applyStyleToRange indicates an expected call of applyStyleToRange.
func (mr *MocktableOperationsMockRecorder) applyStyleToRange(startCol, startRow, endCol, endRow, style any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "applyStyleToRange", reflect.TypeOf((*MocktableOperations)(nil).applyStyleToRange), startCol, startRow, endCol, endRow, style)
}

// getCellValue mocks base method.
func (m *MocktableOperations) getCellValue(col, row int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getCellValue", col, row)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getCellValue indicates an expected call of getCellValue.
func (mr *MocktableOperationsMockRecorder) getCellValue(col, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getCellValue", reflect.TypeOf((*MocktableOperations)(nil).getCellValue), col, row)
}

// getColumnLetter mocks base method.
func (m *MocktableOperations) getColumnLetter(col int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getColumnLetter", col)
	ret0, _ := ret[0].(string)
	return ret0
}

// getColumnLetter indicates an expected call of getColumnLetter.
func (mr *MocktableOperationsMockRecorder) getColumnLetter(col any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getColumnLetter", reflect.TypeOf((*MocktableOperations)(nil).getColumnLetter), col)
}

// getTable mocks base method.
func (m *MocktableOperations) getTable() *go_spit.Table {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getTable")
	ret0, _ := ret[0].(*go_spit.Table)
	return ret0
}

// getTable indicates an expected call of getTable.
func (mr *MocktableOperationsMockRecorder) getTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getTable", reflect.TypeOf((*MocktableOperations)(nil).getTable))
}

// hasExistingBorder mocks base method.
func (m *MocktableOperations) hasExistingBorder(col, row int, side string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "hasExistingBorder", col, row, side)
	ret0, _ := ret[0].(bool)
	return ret0
}

// hasExistingBorder indicates an expected call of hasExistingBorder.
func (mr *MocktableOperationsMockRecorder) hasExistingBorder(col, row, side any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "hasExistingBorder", reflect.TypeOf((*MocktableOperations)(nil).hasExistingBorder), col, row, side)
}

// isCellMerged mocks base method.
func (m *MocktableOperations) isCellMerged(col, row int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "isCellMerged", col, row)
	ret0, _ := ret[0].(bool)
	return ret0
}

// isCellMerged indicates an expected call of isCellMerged.
func (mr *MocktableOperationsMockRecorder) isCellMerged(col, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isCellMerged", reflect.TypeOf((*MocktableOperations)(nil).isCellMerged), col, row)
}

// isCellMergedHorizontally mocks base method.
func (m *MocktableOperations) isCellMergedHorizontally(col, row int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "isCellMergedHorizontally", col, row)
	ret0, _ := ret[0].(bool)
	return ret0
}

// isCellMergedHorizontally indicates an expected call of isCellMergedHorizontally.
func (mr *MocktableOperationsMockRecorder) isCellMergedHorizontally(col, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isCellMergedHorizontally", reflect.TypeOf((*MocktableOperations)(nil).isCellMergedHorizontally), col, row)
}

// mergeCells mocks base method.
func (m *MocktableOperations) mergeCells(startCol, startRow, endCol, endRow int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "mergeCells", startCol, startRow, endCol, endRow)
	ret0, _ := ret[0].(error)
	return ret0
}

// mergeCells indicates an expected call of mergeCells.
func (mr *MocktableOperationsMockRecorder) mergeCells(startCol, startRow, endCol, endRow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mergeCells", reflect.TypeOf((*MocktableOperations)(nil).mergeCells), startCol, startRow, endCol, endRow)
}

// processValue mocks base method.
func (m *MocktableOperations) processValue(value any, format string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "processValue", value, format)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// processValue indicates an expected call of processValue.
func (mr *MocktableOperationsMockRecorder) processValue(value, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "processValue", reflect.TypeOf((*MocktableOperations)(nil).processValue), value, format)
}

// setCellValue mocks base method.
func (m *MocktableOperations) setCellValue(col, row int, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "setCellValue", col, row, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// setCellValue indicates an expected call of setCellValue.
func (mr *MocktableOperationsMockRecorder) setCellValue(col, row, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "setCellValue", reflect.TypeOf((*MocktableOperations)(nil).setCellValue), col, row, value)
}
